/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.inventoris.eve.esi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.inventoris.eve.esi.model.GetCharactersCharacterIdSkillsSkill;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-24T13:09:34.400Z")
public class GetCharactersCharacterIdSkillsOk {
  @SerializedName("skills")
  private List<GetCharactersCharacterIdSkillsSkill> skills = null;

  @SerializedName("total_sp")
  private Long totalSp = null;

  public GetCharactersCharacterIdSkillsOk skills(List<GetCharactersCharacterIdSkillsSkill> skills) {
    this.skills = skills;
    return this;
  }

  public GetCharactersCharacterIdSkillsOk addSkillsItem(GetCharactersCharacterIdSkillsSkill skillsItem) {
    if (this.skills == null) {
      this.skills = new ArrayList<GetCharactersCharacterIdSkillsSkill>();
    }
    this.skills.add(skillsItem);
    return this;
  }

   /**
   * skills array
   * @return skills
  **/
  @ApiModelProperty(value = "skills array")
  public List<GetCharactersCharacterIdSkillsSkill> getSkills() {
    return skills;
  }

  public void setSkills(List<GetCharactersCharacterIdSkillsSkill> skills) {
    this.skills = skills;
  }

  public GetCharactersCharacterIdSkillsOk totalSp(Long totalSp) {
    this.totalSp = totalSp;
    return this;
  }

   /**
   * total_sp integer
   * @return totalSp
  **/
  @ApiModelProperty(value = "total_sp integer")
  public Long getTotalSp() {
    return totalSp;
  }

  public void setTotalSp(Long totalSp) {
    this.totalSp = totalSp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCharactersCharacterIdSkillsOk getCharactersCharacterIdSkillsOk = (GetCharactersCharacterIdSkillsOk) o;
    return Objects.equals(this.skills, getCharactersCharacterIdSkillsOk.skills) &&
        Objects.equals(this.totalSp, getCharactersCharacterIdSkillsOk.totalSp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(skills, totalSp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCharactersCharacterIdSkillsOk {\n");
    
    sb.append("    skills: ").append(toIndentedString(skills)).append("\n");
    sb.append("    totalSp: ").append(toIndentedString(totalSp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

