/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eve.esi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-10T20:23:53.613Z")
public class GetCorporationsCorporationIdOk {
  @SerializedName("alliance_id")
  private Integer allianceId = null;

  @SerializedName("ceo_id")
  private Integer ceoId = null;

  @SerializedName("corporation_description")
  private String corporationDescription = null;

  @SerializedName("corporation_name")
  private String corporationName = null;

  @SerializedName("creation_date")
  private OffsetDateTime creationDate = null;

  @SerializedName("creator_id")
  private Integer creatorId = null;

  /**
   * faction string
   */
  @JsonAdapter(FactionEnum.Adapter.class)
  public enum FactionEnum {
    MINMATAR("Minmatar"),
    
    GALLENTE("Gallente"),
    
    CALDARI("Caldari"),
    
    AMARR("Amarr");

    private String value;

    FactionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FactionEnum fromValue(String text) {
      for (FactionEnum b : FactionEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<FactionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FactionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FactionEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return FactionEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("faction")
  private FactionEnum faction = null;

  @SerializedName("member_count")
  private Integer memberCount = null;

  @SerializedName("tax_rate")
  private Float taxRate = null;

  @SerializedName("ticker")
  private String ticker = null;

  @SerializedName("url")
  private String url = null;

  public GetCorporationsCorporationIdOk allianceId(Integer allianceId) {
    this.allianceId = allianceId;
    return this;
  }

   /**
   * id of alliance that corporation is a member of, if any
   * @return allianceId
  **/
  @ApiModelProperty(value = "id of alliance that corporation is a member of, if any")
  public Integer getAllianceId() {
    return allianceId;
  }

  public void setAllianceId(Integer allianceId) {
    this.allianceId = allianceId;
  }

  public GetCorporationsCorporationIdOk ceoId(Integer ceoId) {
    this.ceoId = ceoId;
    return this;
  }

   /**
   * ceo_id integer
   * @return ceoId
  **/
  @ApiModelProperty(required = true, value = "ceo_id integer")
  public Integer getCeoId() {
    return ceoId;
  }

  public void setCeoId(Integer ceoId) {
    this.ceoId = ceoId;
  }

  public GetCorporationsCorporationIdOk corporationDescription(String corporationDescription) {
    this.corporationDescription = corporationDescription;
    return this;
  }

   /**
   * corporation_description string
   * @return corporationDescription
  **/
  @ApiModelProperty(required = true, value = "corporation_description string")
  public String getCorporationDescription() {
    return corporationDescription;
  }

  public void setCorporationDescription(String corporationDescription) {
    this.corporationDescription = corporationDescription;
  }

  public GetCorporationsCorporationIdOk corporationName(String corporationName) {
    this.corporationName = corporationName;
    return this;
  }

   /**
   * the full name of the corporation
   * @return corporationName
  **/
  @ApiModelProperty(required = true, value = "the full name of the corporation")
  public String getCorporationName() {
    return corporationName;
  }

  public void setCorporationName(String corporationName) {
    this.corporationName = corporationName;
  }

  public GetCorporationsCorporationIdOk creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * creation_date string
   * @return creationDate
  **/
  @ApiModelProperty(value = "creation_date string")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public GetCorporationsCorporationIdOk creatorId(Integer creatorId) {
    this.creatorId = creatorId;
    return this;
  }

   /**
   * creator_id integer
   * @return creatorId
  **/
  @ApiModelProperty(required = true, value = "creator_id integer")
  public Integer getCreatorId() {
    return creatorId;
  }

  public void setCreatorId(Integer creatorId) {
    this.creatorId = creatorId;
  }

  public GetCorporationsCorporationIdOk faction(FactionEnum faction) {
    this.faction = faction;
    return this;
  }

   /**
   * faction string
   * @return faction
  **/
  @ApiModelProperty(value = "faction string")
  public FactionEnum getFaction() {
    return faction;
  }

  public void setFaction(FactionEnum faction) {
    this.faction = faction;
  }

  public GetCorporationsCorporationIdOk memberCount(Integer memberCount) {
    this.memberCount = memberCount;
    return this;
  }

   /**
   * member_count integer
   * @return memberCount
  **/
  @ApiModelProperty(required = true, value = "member_count integer")
  public Integer getMemberCount() {
    return memberCount;
  }

  public void setMemberCount(Integer memberCount) {
    this.memberCount = memberCount;
  }

  public GetCorporationsCorporationIdOk taxRate(Float taxRate) {
    this.taxRate = taxRate;
    return this;
  }

   /**
   * tax_rate number
   * minimum: 0
   * maximum: 1
   * @return taxRate
  **/
  @ApiModelProperty(required = true, value = "tax_rate number")
  public Float getTaxRate() {
    return taxRate;
  }

  public void setTaxRate(Float taxRate) {
    this.taxRate = taxRate;
  }

  public GetCorporationsCorporationIdOk ticker(String ticker) {
    this.ticker = ticker;
    return this;
  }

   /**
   * the short name of the corporation
   * @return ticker
  **/
  @ApiModelProperty(required = true, value = "the short name of the corporation")
  public String getTicker() {
    return ticker;
  }

  public void setTicker(String ticker) {
    this.ticker = ticker;
  }

  public GetCorporationsCorporationIdOk url(String url) {
    this.url = url;
    return this;
  }

   /**
   * url string
   * @return url
  **/
  @ApiModelProperty(required = true, value = "url string")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCorporationsCorporationIdOk getCorporationsCorporationIdOk = (GetCorporationsCorporationIdOk) o;
    return Objects.equals(this.allianceId, getCorporationsCorporationIdOk.allianceId) &&
        Objects.equals(this.ceoId, getCorporationsCorporationIdOk.ceoId) &&
        Objects.equals(this.corporationDescription, getCorporationsCorporationIdOk.corporationDescription) &&
        Objects.equals(this.corporationName, getCorporationsCorporationIdOk.corporationName) &&
        Objects.equals(this.creationDate, getCorporationsCorporationIdOk.creationDate) &&
        Objects.equals(this.creatorId, getCorporationsCorporationIdOk.creatorId) &&
        Objects.equals(this.faction, getCorporationsCorporationIdOk.faction) &&
        Objects.equals(this.memberCount, getCorporationsCorporationIdOk.memberCount) &&
        Objects.equals(this.taxRate, getCorporationsCorporationIdOk.taxRate) &&
        Objects.equals(this.ticker, getCorporationsCorporationIdOk.ticker) &&
        Objects.equals(this.url, getCorporationsCorporationIdOk.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allianceId, ceoId, corporationDescription, corporationName, creationDate, creatorId, faction, memberCount, taxRate, ticker, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCorporationsCorporationIdOk {\n");
    
    sb.append("    allianceId: ").append(toIndentedString(allianceId)).append("\n");
    sb.append("    ceoId: ").append(toIndentedString(ceoId)).append("\n");
    sb.append("    corporationDescription: ").append(toIndentedString(corporationDescription)).append("\n");
    sb.append("    corporationName: ").append(toIndentedString(corporationName)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    creatorId: ").append(toIndentedString(creatorId)).append("\n");
    sb.append("    faction: ").append(toIndentedString(faction)).append("\n");
    sb.append("    memberCount: ").append(toIndentedString(memberCount)).append("\n");
    sb.append("    taxRate: ").append(toIndentedString(taxRate)).append("\n");
    sb.append("    ticker: ").append(toIndentedString(ticker)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

