#!/bin/bash
docker run --rm -v ${PWD}:/local \
    swaggerapi/swagger-codegen-cli \
    generate \
    -i "https://esi.tech.ccp.is/_latest/swagger.json" \
    -l java \
    --model-package de.inventoris.eve.esi.model \
    --invoker-package de.inventoris.eve.esi.invoke \
    --api-package de.inventoris.eve.esi.api \
    -o /local/java-client
