/*
 * EVEMarketer Marketstat API
 * EVEMarketer Marketstat API is almost compatible with EVE-Central's Marketstat API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketer.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import marketer.model.MarketStatXML;

/**
 * ExecAPI
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-30T13:45:53.814Z")
public class ExecAPI {
  @SerializedName("version")
  private String version = null;

  @SerializedName("method")
  private String method = null;

  @SerializedName("marketstat")
  private MarketStatXML marketstat = null;

  public ExecAPI version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(example = "2.0", value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public ExecAPI method(String method) {
    this.method = method;
    return this;
  }

   /**
   * Get method
   * @return method
  **/
  @ApiModelProperty(example = "marketstat_xml", value = "")
  public String getMethod() {
    return method;
  }

  public void setMethod(String method) {
    this.method = method;
  }

  public ExecAPI marketstat(MarketStatXML marketstat) {
    this.marketstat = marketstat;
    return this;
  }

   /**
   * Get marketstat
   * @return marketstat
  **/
  @ApiModelProperty(value = "")
  public MarketStatXML getMarketstat() {
    return marketstat;
  }

  public void setMarketstat(MarketStatXML marketstat) {
    this.marketstat = marketstat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecAPI execAPI = (ExecAPI) o;
    return Objects.equals(this.version, execAPI.version) &&
        Objects.equals(this.method, execAPI.method) &&
        Objects.equals(this.marketstat, execAPI.marketstat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, method, marketstat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecAPI {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    marketstat: ").append(toIndentedString(marketstat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

