/*
 * EVEMarketer Marketstat API
 * EVEMarketer Marketstat API is almost compatible with EVE-Central's Marketstat API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketer.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import marketer.model.TypeStatXML;

/**
 * MarketStatXMLInner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-30T13:45:53.814Z")
public class MarketStatXMLInner {
  @SerializedName("buy")
  private TypeStatXML buy = null;

  @SerializedName("sell")
  private TypeStatXML sell = null;

  public MarketStatXMLInner buy(TypeStatXML buy) {
    this.buy = buy;
    return this;
  }

   /**
   * Get buy
   * @return buy
  **/
  @ApiModelProperty(value = "")
  public TypeStatXML getBuy() {
    return buy;
  }

  public void setBuy(TypeStatXML buy) {
    this.buy = buy;
  }

  public MarketStatXMLInner sell(TypeStatXML sell) {
    this.sell = sell;
    return this;
  }

   /**
   * Get sell
   * @return sell
  **/
  @ApiModelProperty(value = "")
  public TypeStatXML getSell() {
    return sell;
  }

  public void setSell(TypeStatXML sell) {
    this.sell = sell;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketStatXMLInner marketStatXMLInner = (MarketStatXMLInner) o;
    return Objects.equals(this.buy, marketStatXMLInner.buy) &&
        Objects.equals(this.sell, marketStatXMLInner.sell);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buy, sell);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketStatXMLInner {\n");
    
    sb.append("    buy: ").append(toIndentedString(buy)).append("\n");
    sb.append("    sell: ").append(toIndentedString(sell)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

