/*
 * EVEMarketer Marketstat API
 * EVEMarketer Marketstat API is almost compatible with EVE-Central's Marketstat API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketer.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import marketer.model.ForQuery;

/**
 * TypeStat
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-30T13:45:53.814Z")
public class TypeStat {
  @SerializedName("forQuery")
  private ForQuery forQuery = null;

  @SerializedName("volume")
  private Long volume = null;

  @SerializedName("wavg")
  private Double wavg = null;

  @SerializedName("avg")
  private Double avg = null;

  @SerializedName("min")
  private Double min = null;

  @SerializedName("max")
  private Double max = null;

  @SerializedName("variance")
  private Double variance = null;

  @SerializedName("stdDev")
  private Double stdDev = null;

  @SerializedName("median")
  private Double median = null;

  @SerializedName("fivePercent")
  private Double fivePercent = null;

  @SerializedName("highToLow")
  private Boolean highToLow = null;

  @SerializedName("generated")
  private Long generated = null;

  public TypeStat forQuery(ForQuery forQuery) {
    this.forQuery = forQuery;
    return this;
  }

   /**
   * Get forQuery
   * @return forQuery
  **/
  @ApiModelProperty(value = "")
  public ForQuery getForQuery() {
    return forQuery;
  }

  public void setForQuery(ForQuery forQuery) {
    this.forQuery = forQuery;
  }

  public TypeStat volume(Long volume) {
    this.volume = volume;
    return this;
  }

   /**
   * Order Volume
   * @return volume
  **/
  @ApiModelProperty(example = "963208", value = "Order Volume")
  public Long getVolume() {
    return volume;
  }

  public void setVolume(Long volume) {
    this.volume = volume;
  }

  public TypeStat wavg(Double wavg) {
    this.wavg = wavg;
    return this;
  }

   /**
   * Weighted Average Price
   * @return wavg
  **/
  @ApiModelProperty(example = "3204519.59", value = "Weighted Average Price")
  public Double getWavg() {
    return wavg;
  }

  public void setWavg(Double wavg) {
    this.wavg = wavg;
  }

  public TypeStat avg(Double avg) {
    this.avg = avg;
    return this;
  }

   /**
   * Average Price
   * @return avg
  **/
  @ApiModelProperty(example = "3352708.11", value = "Average Price")
  public Double getAvg() {
    return avg;
  }

  public void setAvg(Double avg) {
    this.avg = avg;
  }

  public TypeStat min(Double min) {
    this.min = min;
    return this;
  }

   /**
   * Get min
   * @return min
  **/
  @ApiModelProperty(example = "2601400.03", value = "")
  public Double getMin() {
    return min;
  }

  public void setMin(Double min) {
    this.min = min;
  }

  public TypeStat max(Double max) {
    this.max = max;
    return this;
  }

   /**
   * Get max
   * @return max
  **/
  @ApiModelProperty(example = "1.0E7", value = "")
  public Double getMax() {
    return max;
  }

  public void setMax(Double max) {
    this.max = max;
  }

  public TypeStat variance(Double variance) {
    this.variance = variance;
    return this;
  }

   /**
   * Get variance
   * @return variance
  **/
  @ApiModelProperty(example = "7.6981542253724E11", value = "")
  public Double getVariance() {
    return variance;
  }

  public void setVariance(Double variance) {
    this.variance = variance;
  }

  public TypeStat stdDev(Double stdDev) {
    this.stdDev = stdDev;
    return this;
  }

   /**
   * Standard Deviation
   * @return stdDev
  **/
  @ApiModelProperty(example = "877391.25", value = "Standard Deviation")
  public Double getStdDev() {
    return stdDev;
  }

  public void setStdDev(Double stdDev) {
    this.stdDev = stdDev;
  }

  public TypeStat median(Double median) {
    this.median = median;
    return this;
  }

   /**
   * Median Price
   * @return median
  **/
  @ApiModelProperty(example = "3094978.97", value = "Median Price")
  public Double getMedian() {
    return median;
  }

  public void setMedian(Double median) {
    this.median = median;
  }

  public TypeStat fivePercent(Double fivePercent) {
    this.fivePercent = fivePercent;
    return this;
  }

   /**
   * Get fivePercent
   * @return fivePercent
  **/
  @ApiModelProperty(example = "2949353.31", value = "")
  public Double getFivePercent() {
    return fivePercent;
  }

  public void setFivePercent(Double fivePercent) {
    this.fivePercent = fivePercent;
  }

  public TypeStat highToLow(Boolean highToLow) {
    this.highToLow = highToLow;
    return this;
  }

   /**
   * Get highToLow
   * @return highToLow
  **/
  @ApiModelProperty(value = "")
  public Boolean isHighToLow() {
    return highToLow;
  }

  public void setHighToLow(Boolean highToLow) {
    this.highToLow = highToLow;
  }

  public TypeStat generated(Long generated) {
    this.generated = generated;
    return this;
  }

   /**
   * Generated at (UNIX Timestamp msec)
   * @return generated
  **/
  @ApiModelProperty(example = "1499280224508", value = "Generated at (UNIX Timestamp msec)")
  public Long getGenerated() {
    return generated;
  }

  public void setGenerated(Long generated) {
    this.generated = generated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TypeStat typeStat = (TypeStat) o;
    return Objects.equals(this.forQuery, typeStat.forQuery) &&
        Objects.equals(this.volume, typeStat.volume) &&
        Objects.equals(this.wavg, typeStat.wavg) &&
        Objects.equals(this.avg, typeStat.avg) &&
        Objects.equals(this.min, typeStat.min) &&
        Objects.equals(this.max, typeStat.max) &&
        Objects.equals(this.variance, typeStat.variance) &&
        Objects.equals(this.stdDev, typeStat.stdDev) &&
        Objects.equals(this.median, typeStat.median) &&
        Objects.equals(this.fivePercent, typeStat.fivePercent) &&
        Objects.equals(this.highToLow, typeStat.highToLow) &&
        Objects.equals(this.generated, typeStat.generated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(forQuery, volume, wavg, avg, min, max, variance, stdDev, median, fivePercent, highToLow, generated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TypeStat {\n");
    
    sb.append("    forQuery: ").append(toIndentedString(forQuery)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("    wavg: ").append(toIndentedString(wavg)).append("\n");
    sb.append("    avg: ").append(toIndentedString(avg)).append("\n");
    sb.append("    min: ").append(toIndentedString(min)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    variance: ").append(toIndentedString(variance)).append("\n");
    sb.append("    stdDev: ").append(toIndentedString(stdDev)).append("\n");
    sb.append("    median: ").append(toIndentedString(median)).append("\n");
    sb.append("    fivePercent: ").append(toIndentedString(fivePercent)).append("\n");
    sb.append("    highToLow: ").append(toIndentedString(highToLow)).append("\n");
    sb.append("    generated: ").append(toIndentedString(generated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

