/*
 * EVEMarketer Marketstat API
 * EVEMarketer Marketstat API is almost compatible with EVE-Central's Marketstat API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketer.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TypeStatXML
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-30T13:45:53.814Z")
public class TypeStatXML {
  @SerializedName("volume")
  private Long volume = null;

  @SerializedName("avg")
  private Double avg = null;

  @SerializedName("max")
  private Double max = null;

  @SerializedName("min")
  private Double min = null;

  @SerializedName("stddev")
  private Double stddev = null;

  @SerializedName("median")
  private Double median = null;

  @SerializedName("percentile")
  private Double percentile = null;

  public TypeStatXML volume(Long volume) {
    this.volume = volume;
    return this;
  }

   /**
   * Order Volume
   * @return volume
  **/
  @ApiModelProperty(example = "963208", value = "Order Volume")
  public Long getVolume() {
    return volume;
  }

  public void setVolume(Long volume) {
    this.volume = volume;
  }

  public TypeStatXML avg(Double avg) {
    this.avg = avg;
    return this;
  }

   /**
   * Weighted Average Price
   * @return avg
  **/
  @ApiModelProperty(example = "3204519.59", value = "Weighted Average Price")
  public Double getAvg() {
    return avg;
  }

  public void setAvg(Double avg) {
    this.avg = avg;
  }

  public TypeStatXML max(Double max) {
    this.max = max;
    return this;
  }

   /**
   * Maximum Price
   * @return max
  **/
  @ApiModelProperty(example = "1.0E7", value = "Maximum Price")
  public Double getMax() {
    return max;
  }

  public void setMax(Double max) {
    this.max = max;
  }

  public TypeStatXML min(Double min) {
    this.min = min;
    return this;
  }

   /**
   * Minimum Price
   * @return min
  **/
  @ApiModelProperty(example = "2601400.03", value = "Minimum Price")
  public Double getMin() {
    return min;
  }

  public void setMin(Double min) {
    this.min = min;
  }

  public TypeStatXML stddev(Double stddev) {
    this.stddev = stddev;
    return this;
  }

   /**
   * Standard Deviation
   * @return stddev
  **/
  @ApiModelProperty(example = "877391.25", value = "Standard Deviation")
  public Double getStddev() {
    return stddev;
  }

  public void setStddev(Double stddev) {
    this.stddev = stddev;
  }

  public TypeStatXML median(Double median) {
    this.median = median;
    return this;
  }

   /**
   * Median Price
   * @return median
  **/
  @ApiModelProperty(example = "3094978.97", value = "Median Price")
  public Double getMedian() {
    return median;
  }

  public void setMedian(Double median) {
    this.median = median;
  }

  public TypeStatXML percentile(Double percentile) {
    this.percentile = percentile;
    return this;
  }

   /**
   * 5% Price
   * @return percentile
  **/
  @ApiModelProperty(example = "2949353.31", value = "5% Price")
  public Double getPercentile() {
    return percentile;
  }

  public void setPercentile(Double percentile) {
    this.percentile = percentile;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TypeStatXML typeStatXML = (TypeStatXML) o;
    return Objects.equals(this.volume, typeStatXML.volume) &&
        Objects.equals(this.avg, typeStatXML.avg) &&
        Objects.equals(this.max, typeStatXML.max) &&
        Objects.equals(this.min, typeStatXML.min) &&
        Objects.equals(this.stddev, typeStatXML.stddev) &&
        Objects.equals(this.median, typeStatXML.median) &&
        Objects.equals(this.percentile, typeStatXML.percentile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(volume, avg, max, min, stddev, median, percentile);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TypeStatXML {\n");
    
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("    avg: ").append(toIndentedString(avg)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    min: ").append(toIndentedString(min)).append("\n");
    sb.append("    stddev: ").append(toIndentedString(stddev)).append("\n");
    sb.append("    median: ").append(toIndentedString(median)).append("\n");
    sb.append("    percentile: ").append(toIndentedString(percentile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

