/*
 * EVEMarketer Marketstat API
 * EVEMarketer Marketstat API is almost compatible with EVE-Central's Marketstat API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketer.api;

import marketer.invoke.ApiException;
import marketer.model.ExecAPI;
import marketer.model.Type;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MarketstatApi
 */
@Ignore
public class MarketstatApiTest {

    private final MarketstatApi api = new MarketstatApi();

    
    /**
     * XML Marketstat
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void marketstatGetTest() throws ApiException {
        List<Integer> typeid = null;
        Integer regionlimit = null;
        Integer usesystem = null;
        ExecAPI response = api.marketstatGet(typeid, regionlimit, usesystem);

        // TODO: test validations
    }
    
    /**
     * JSON Marketstat
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void marketstatJsonGetTest() throws ApiException {
        List<Integer> typeid = null;
        Integer regionlimit = null;
        Integer usesystem = null;
        List<Type> response = api.marketstatJsonGet(typeid, regionlimit, usesystem);

        // TODO: test validations
    }
    
}
