/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eve.esi.api;

import eve.esi.invoke.ApiException;
import eve.esi.model.Forbidden;
import eve.esi.model.GetCharactersCharacterIdContracts200Ok;
import eve.esi.model.GetCharactersCharacterIdContractsContractIdBids200Ok;
import eve.esi.model.GetCharactersCharacterIdContractsContractIdItems200Ok;
import eve.esi.model.InternalServerError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContractsApi
 */
@Ignore
public class ContractsApiTest {

    private final ContractsApi api = new ContractsApi();

    
    /**
     * Get contracts
     *
     * Returns contracts available to a character, only if the character is issuer, acceptor or assignee. Only returns contracts no older than 30 days, or if the status is \&quot;in_progress\&quot;.  ---  This route is cached for up to 300 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdContractsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdContracts200Ok> response = api.getCharactersCharacterIdContracts(characterId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get contract bids
     *
     * Lists bids on a particular auction contract  ---  This route is cached for up to 300 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdContractsContractIdBidsTest() throws ApiException {
        Integer characterId = null;
        Integer contractId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdContractsContractIdBids200Ok> response = api.getCharactersCharacterIdContractsContractIdBids(characterId, contractId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get contract items
     *
     * Lists Items and details of a particular contract  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdContractsContractIdItemsTest() throws ApiException {
        Integer characterId = null;
        Integer contractId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdContractsContractIdItems200Ok> response = api.getCharactersCharacterIdContractsContractIdItems(characterId, contractId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
