/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eve.esi.api;

import eve.esi.invoke.ApiException;
import eve.esi.model.Forbidden;
import eve.esi.model.GetCorporationsCorporationIdAlliancehistory200Ok;
import eve.esi.model.GetCorporationsCorporationIdBlueprints200Ok;
import eve.esi.model.GetCorporationsCorporationIdDivisionsOk;
import eve.esi.model.GetCorporationsCorporationIdIconsNotFound;
import eve.esi.model.GetCorporationsCorporationIdIconsOk;
import eve.esi.model.GetCorporationsCorporationIdMembers200Ok;
import eve.esi.model.GetCorporationsCorporationIdMembertracking200Ok;
import eve.esi.model.GetCorporationsCorporationIdNotFound;
import eve.esi.model.GetCorporationsCorporationIdOk;
import eve.esi.model.GetCorporationsCorporationIdRoles200Ok;
import eve.esi.model.GetCorporationsCorporationIdStructures200Ok;
import eve.esi.model.GetCorporationsCorporationIdTitles200Ok;
import eve.esi.model.GetCorporationsNames200Ok;
import eve.esi.model.InternalServerError;
import eve.esi.model.PutCorporationsCorporationIdStructuresStructureIdNewSchedule;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CorporationApi
 */
@Ignore
public class CorporationApiTest {

    private final CorporationApi api = new CorporationApi();

    
    /**
     * Get corporation information
     *
     * Public information about a corporation  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetCorporationsCorporationIdOk response = api.getCorporationsCorporationId(corporationId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get alliance history
     *
     * Get a list of all the alliances a corporation has been a member of  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdAlliancehistoryTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdAlliancehistory200Ok> response = api.getCorporationsCorporationIdAlliancehistory(corporationId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation blueprints
     *
     * Returns a list of blueprints the corporation owns  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdBlueprintsTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        Integer page = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdBlueprints200Ok> response = api.getCorporationsCorporationIdBlueprints(corporationId, datasource, page, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation divisions
     *
     * Return corporation hangar and wallet division names, only show if a division is not using the default name  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdDivisionsTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        GetCorporationsCorporationIdDivisionsOk response = api.getCorporationsCorporationIdDivisions(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation icon
     *
     * Get the icon urls for a corporation  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdIconsTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetCorporationsCorporationIdIconsOk response = api.getCorporationsCorporationIdIcons(corporationId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation members
     *
     * Read the current list of members if the calling character is a member.  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMembersTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdMembers200Ok> response = api.getCorporationsCorporationIdMembers(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation member limit
     *
     * Return a corporation&#39;s member limit, not including CEO himself  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMembersLimitTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        Integer response = api.getCorporationsCorporationIdMembersLimit(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Track corporation members
     *
     * Returns additional information about a corporation&#39;s members which helps tracking their activities  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMembertrackingTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdMembertracking200Ok> response = api.getCorporationsCorporationIdMembertracking(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation member roles
     *
     * Return the roles of all members if the character has the personnel manager role or any grantable role.  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdRolesTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdRoles200Ok> response = api.getCorporationsCorporationIdRoles(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation structures
     *
     * Get a list of corporation structures  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdStructuresTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String language = null;
        Integer page = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdStructures200Ok> response = api.getCorporationsCorporationIdStructures(corporationId, datasource, language, page, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation titles
     *
     * Returns a corporation&#39;s titles  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdTitlesTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdTitles200Ok> response = api.getCorporationsCorporationIdTitles(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation names
     *
     * Resolve a set of corporation IDs to corporation names  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsNamesTest() throws ApiException {
        List<Long> corporationIds = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsNames200Ok> response = api.getCorporationsNames(corporationIds, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get npc corporations
     *
     * Get a list of npc corporations  ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsNpccorpsTest() throws ApiException {
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getCorporationsNpccorps(datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Update structure vulnerability schedule
     *
     * Update the vulnerability window schedule of a corporation structure  --- 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putCorporationsCorporationIdStructuresStructureIdTest() throws ApiException {
        Integer corporationId = null;
        List<PutCorporationsCorporationIdStructuresStructureIdNewSchedule> newSchedule = null;
        Long structureId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.putCorporationsCorporationIdStructuresStructureId(corporationId, newSchedule, structureId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
