/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eve.esi.api;

import eve.esi.invoke.ApiException;
import eve.esi.model.Forbidden;
import eve.esi.model.GetCharactersCharacterIdIndustryJobs200Ok;
import eve.esi.model.GetIndustryFacilities200Ok;
import eve.esi.model.GetIndustrySystems200Ok;
import eve.esi.model.InternalServerError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IndustryApi
 */
@Ignore
public class IndustryApiTest {

    private final IndustryApi api = new IndustryApi();

    
    /**
     * List character industry jobs
     *
     * List industry jobs placed by a character  ---  This route is cached for up to 300 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdIndustryJobsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        Boolean includeCompleted = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdIndustryJobs200Ok> response = api.getCharactersCharacterIdIndustryJobs(characterId, datasource, includeCompleted, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * List industry facilities
     *
     * Return a list of industry facilities  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIndustryFacilitiesTest() throws ApiException {
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetIndustryFacilities200Ok> response = api.getIndustryFacilities(datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * List solar system cost indices
     *
     * Return cost indices for solar systems  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIndustrySystemsTest() throws ApiException {
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetIndustrySystems200Ok> response = api.getIndustrySystems(datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
