/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eve.esi.api;

import eve.esi.invoke.ApiException;
import eve.esi.model.DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity;
import eve.esi.model.Forbidden;
import eve.esi.model.GetCharactersCharacterIdMail200Ok;
import eve.esi.model.GetCharactersCharacterIdMailLabelsOk;
import eve.esi.model.GetCharactersCharacterIdMailLists200Ok;
import eve.esi.model.GetCharactersCharacterIdMailMailIdNotFound;
import eve.esi.model.GetCharactersCharacterIdMailMailIdOk;
import eve.esi.model.InternalServerError;
import eve.esi.model.PostCharactersCharacterIdMailBadRequest;
import eve.esi.model.PostCharactersCharacterIdMailLabelsLabel;
import eve.esi.model.PostCharactersCharacterIdMailMail;
import eve.esi.model.PutCharactersCharacterIdMailMailIdBadRequest;
import eve.esi.model.PutCharactersCharacterIdMailMailIdContents;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MailApi
 */
@Ignore
public class MailApiTest {

    private final MailApi api = new MailApi();

    
    /**
     * Delete a mail label
     *
     * Delete a mail label  --- 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCharactersCharacterIdMailLabelsLabelIdTest() throws ApiException {
        Integer characterId = null;
        Integer labelId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.deleteCharactersCharacterIdMailLabelsLabelId(characterId, labelId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Delete a mail
     *
     * Delete a mail  --- 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCharactersCharacterIdMailMailIdTest() throws ApiException {
        Integer characterId = null;
        Integer mailId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.deleteCharactersCharacterIdMailMailId(characterId, mailId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Return mail headers
     *
     * Return the 50 most recent mail headers belonging to the character that match the query criteria. Queries can be filtered by label, and last_mail_id can be used to paginate backwards.  ---  This route is cached for up to 30 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdMailTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        List<Long> labels = null;
        Integer lastMailId = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdMail200Ok> response = api.getCharactersCharacterIdMail(characterId, datasource, labels, lastMailId, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get mail labels and unread counts
     *
     * Return a list of the users mail labels, unread counts for each label and a total unread count.  ---  This route is cached for up to 30 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdMailLabelsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        GetCharactersCharacterIdMailLabelsOk response = api.getCharactersCharacterIdMailLabels(characterId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Return mailing list subscriptions
     *
     * Return all mailing lists that the character is subscribed to  ---  This route is cached for up to 120 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdMailListsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdMailLists200Ok> response = api.getCharactersCharacterIdMailLists(characterId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Return a mail
     *
     * Return the contents of an EVE mail  ---  This route is cached for up to 30 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdMailMailIdTest() throws ApiException {
        Integer characterId = null;
        Integer mailId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        GetCharactersCharacterIdMailMailIdOk response = api.getCharactersCharacterIdMailMailId(characterId, mailId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Send a new mail
     *
     * Create and send a new mail  --- 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCharactersCharacterIdMailTest() throws ApiException {
        Integer characterId = null;
        PostCharactersCharacterIdMailMail mail = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        Integer response = api.postCharactersCharacterIdMail(characterId, mail, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Create a mail label
     *
     * Create a mail label  --- 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCharactersCharacterIdMailLabelsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        PostCharactersCharacterIdMailLabelsLabel label = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        Long response = api.postCharactersCharacterIdMailLabels(characterId, datasource, label, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Update metadata about a mail
     *
     * Update metadata about a mail  --- 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putCharactersCharacterIdMailMailIdTest() throws ApiException {
        Integer characterId = null;
        PutCharactersCharacterIdMailMailIdContents contents = null;
        Integer mailId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.putCharactersCharacterIdMailMailId(characterId, contents, mailId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
